In [11]:
#Tuples
student = ("Mithu",25,"CS")
print(student)
print(student[1])

#list-> mutable
#tuple->immutable

('Mithu', 25, 'CS')
25

In [12]:
#Disctionaries
student = {
    "name" : "Mithu",
    "age" : 25,
    "course" : "CS"
}

print(student["name"])
print(student["age"])

Mithu
25

In [18]:
#Functions
def calculate_average1(a,b):
    return (a+b)/2
def calculate2(a,b):
    return (a-b)
def calculate3(a,b):
    return (a*b)
def calculate4(a,b):
    return (a/b)
def calculate5(a,b):
    return (a+b)

result1 = calculate_average1(20,30)
print(result1)
result2 = calculate2(40,30)
print(result2)
result3 = calculate3(20,30)
print(result3)
result4 = calculate4(60,30)
print(result4)
result5 = calculate5(60,30)
print(result5)

25.0
10
600
2.0
90

In [20]:
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers)
print(numbers.mean())

[10 20 30 40 50]
30.0

In [22]:
import pandas as pd

In [45]:
#df = data frame
df = pd.read_csv("data1.csv")

In [36]:
df.head()

   Age  Gender  Study_Hours  Attendance  Assignment_Score  Final_Score
0   20  Female            8          90                75           82
1   21    Male            5          78                68           70
2   19  Female           10          95                88           91

In [37]:
df.tail()

   Age  Gender  Study_Hours  Attendance  Assignment_Score  Final_Score
0   20  Female            8          90                75           82
1   21    Male            5          78                68           70
2   19  Female           10          95                88           91

In [39]:
df.shape

(3, 6)

In [42]:
df.columns

Index(['Age', 'Gender', 'Study_Hours', 'Attendance', 'Assignment_Score',
       'Final_Score'],
      dtype='object')

In [46]:
df.dtypes

Age                  int64
Gender              object
Study_Hours          int64
Attendance           int64
Assignment_Score     int64
Final_Score          int64
dtype: object

In [47]:
df = pd.read_csv("data2.csv")

In [50]:
df.tail()

    Day  Temperature  Humidity  Wind_Speed  Rainfall  Cloud_Cover Umbrella
15   16           28        89          19      11.6           92      Yes
16   17           31        72          12       2.1           60      Yes
17   18           34        62           7       0.0           22       No
18   19           29        83          17       6.9           78      Yes
19   20           32        69           9       0.0           38       No

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          20 non-null     int64
 1   Temperature  20 non-null     int64
 2   Humidity     20 non-null     int64
 3   Wind_Speed   20 non-null     int64
 4   Rainfall     20 non-null     float64
 5   Cloud_Cover  20 non-null     int64
 6   Umbrella     20 non-null     object
dtypes: float64(1), int64(5), object(1)
memory usage: 1.2+ KB

In [53]:
df = pd.read_csv("data1.csv")

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               3 non-null      int64
 1   Gender            3 non-null      object
 2   Study_Hours       3 non-null      int64
 3   Attendance        3 non-null      int64
 4   Assignment_Score  3 non-null      int64
 5   Final_Score       3 non-null      int64
dtypes: int64(5), object(1)
memory usage: 272.0+ bytes

In [55]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [57]:
df["Gender"].value_counts()

Female    2
Male      1
Name: Gender, dtype: int64

In [60]:
df.describe()

        Age  Study_Hours  Attendance  Assignment_Score  Final_Score
count   3.0     3.000000    3.000000          3.000000     3.000000
mean   20.0     7.666667   87.666667         77.000000    81.000000
std     1.0     2.516611    8.736895         10.148892    10.535654
min    19.0     5.000000   78.000000         68.000000    70.000000
25%    19.5     6.500000   84.000000         71.500000    76.000000
50%    20.0     8.000000   90.000000         75.000000    82.000000
75%    20.5     9.000000   92.500000         81.500000    86.500000
max    21.0    10.000000   95.000000         88.000000    91.000000

In [62]:
df["Study_Hours"].mean()

7.666666666666667

In [64]:
df["Study_Hours"].median()

8.0

In [66]:
df["Study_Hours"].mode()

0     5
1     8
2    10
Name: Study_Hours, dtype: int64

In [68]:
df["Study_Hours"].min()

5

In [70]:
df["Study_Hours"].max()

10

In [72]:
df["Study_Hours"].std()

2.516611478423583

In [78]:
df.isnull().sum()

Age                 0
Gender              0
Study_Hours         0
Attendance          0
Assignment_Score    0
Final_Score         0
dtype: int64

In [80]:
df.isnull().sum().sum()

0

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data2.csv")

In [5]:
df

    Day  Temperature  Humidity  Wind_Speed  Rainfall  Cloud_Cover Umbrella
0     1           30        75          12       2.5           65      Yes
1     2           32        68          10       0.0           35       No
2     3           29        82          15       8.2           80      Yes
3     4           31        70           8       0.5           40       No
4     5           28        88          18      12.4           90      Yes
5     6           33        65           7       0.0           25       No
6     7           30        79          14       4.6           70      Yes
7     8           34        60           9       0.0           20       No
8     9           27        91          20      15.8           95      Yes
9    10           31        73          11       1.2           55      Yes
10   11           32        67           8       0.0           30       No
11   12           29        85          16       7.5           82      Yes
12   13           35        58           6       0.0           15       No
13   14           30        77          13       3.8           68      Yes
14   15           33        64          10       0.0           28       No
15   16           28        89          19      11.6           92      Yes
16   17           31        72          12       2.1           60      Yes
17   18           34        62           7       0.0           22       No
18   19           29        83          17       6.9           78      Yes
19   20           32        69           9       0.0           38       No

In [6]:
df.head()

   Day  Temperature  Humidity  Wind_Speed  Rainfall  Cloud_Cover Umbrella
0    1           30        75          12       2.5           65      Yes
1    2           32        68          10       0.0           35       No
2    3           29        82          15       8.2           80      Yes
3    4           31        70           8       0.5           40       No
4    5           28        88          18      12.4           90      Yes

In [7]:
df.tail()

    Day  Temperature  Humidity  Wind_Speed  Rainfall  Cloud_Cover Umbrella
15   16           28        89          19      11.6           92      Yes
16   17           31        72          12       2.1           60      Yes
17   18           34        62           7       0.0           22       No
18   19           29        83          17       6.9           78      Yes
19   20           32        69           9       0.0           38       No

In [87]:
df.shape

(20, 7)

In [89]:
df.columns

Index(['Day', 'Temperature', 'Humidity', 'Wind_Speed', 'Rainfall',
       'Cloud_Cover', 'Umbrella'],
      dtype='object')

In [92]:
df.dtypes

Day              int64
Temperature      int64
Humidity         int64
Wind_Speed       int64
Rainfall       float64
Cloud_Cover      int64
Umbrella        object
dtype: object

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          20 non-null     int64
 1   Temperature  20 non-null     int64
 2   Humidity     20 non-null     int64
 3   Wind_Speed   20 non-null     int64
 4   Rainfall     20 non-null     float64
 5   Cloud_Cover  20 non-null     int64
 6   Umbrella     20 non-null     object
dtypes: float64(1), int64(5), object(1)
memory usage: 1.2+ KB

In [8]:
df["Temperature"]

0     30
1     32
2     29
3     31
4     28
5     33
6     30
7     34
8     27
9     31
10    32
11    29
12    35
13    30
14    33
15    28
16    31
17    34
18    29
19    32
Name: Temperature, dtype: int64

In [9]:
df[["Temperature","Humidity"]]

    Temperature  Humidity
0            30        75
1            32        68
2            29        82
3            31        70
4            28        88
5            33        65
6            30        79
7            34        60
8            27        91
9            31        73
10           32        67
11           29        85
12           35        58
13           30        77
14           33        64
15           28        89
16           31        72
17           34        62
18           29        83
19           32        69

In [10]:
df["Rainfall"]

0      2.5
1      0.0
2      8.2
3      0.5
4     12.4
5      0.0
6      4.6
7      0.0
8     15.8
9      1.2
10     0.0
11     7.5
12     0.0
13     3.8
14     0.0
15    11.6
16     2.1
17     0.0
18     6.9
19     0.0
Name: Rainfall, dtype: float64

In [103]:
df["Temperature"].head(10)

0    30
1    32
2    29
3    31
4    28
5    33
6    30
7    34
8    27
9    31
Name: Temperature, dtype: int64

In [105]:
df.describe()

            Day  Temperature   Humidity  Wind_Speed   Rainfall  Cloud_Cover
count  20.00000    20.000000  20.000000   20.000000  20.000000    20.000000
mean   10.50000    30.900000  73.850000   12.050000   3.855000    54.400000
std     5.91608     2.221901  10.048697    4.285533   4.919293    26.823791
min     1.00000    27.000000  58.000000    6.000000   0.000000    15.000000
25%     5.75000    29.000000  66.500000    8.750000   0.000000    29.500000
50%    10.50000    31.000000  72.500000   11.500000   1.650000    57.500000
75%    15.25000    32.250000  82.250000   15.250000   7.050000    78.500000
max    20.00000    35.000000  91.000000   20.000000  15.800000    95.000000

In [107]:
df["Temperature"].mean()

30.9

In [109]:
df["Temperature"].min()

27

In [110]:
df["Temperature"].max()

35

In [111]:
df["Temperature"].median()

31.0

In [112]:
df["Humidity"].mean()

73.85

In [113]:
df["Rainfall"].max()

15.8

In [114]:
df["Rainfall"].min()

0.0

In [115]:
df["Wind_Speed"].mean()

12.05

In [116]:
df["Temperature"].std()

2.2219005615155596

In [11]:
df["Umbrella"].unique()

array(['Yes', 'No'], dtype=object)

In [12]:
df["Umbrella"].value_counts()

Yes    11
No      9
Name: Umbrella, dtype: int64

In [14]:
df["Umbrella"].nunique()

2

In [125]:
df.isnull().sum()

Day            0
Temperature    0
Humidity       0
Wind_Speed     0
Rainfall       0
Cloud_Cover    0
Umbrella       0
dtype: int64

In [15]:
df.isnull().sum().sum()

0